<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="OpenTK" Version="4.9.4" />
    <PackageReference Include="StbiSharp" Version="1.2.1" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Graphics/Shaders/*.vert" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="Graphics/Shaders/*.frag" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Audio\**" />
    <Compile Remove="FileResources\**" />
    <Compile Remove="GameResources\**" />
    <Compile Remove="Input\**" />
    <Compile Remove="Physics\**" />
    <Content Remove="Audio\**" />
    <Content Remove="FileResources\**" />
    <Content Remove="GameResources\**" />
    <Content Remove="Input\**" />
    <Content Remove="Physics\**" />
    <EmbeddedResource Remove="Audio\**" />
    <EmbeddedResource Remove="FileResources\**" />
    <EmbeddedResource Remove="GameResources\**" />
    <EmbeddedResource Remove="Input\**" />
    <EmbeddedResource Remove="Physics\**" />
    <None Remove="Audio\**" />
    <None Remove="FileResources\**" />
    <None Remove="GameResources\**" />
    <None Remove="Input\**" />
    <None Remove="Physics\**" />
  </ItemGroup>
</Project>
